/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

// RCC
#define RCC_AHB1ENR   (*(volatile uint32_t *)0x40023830)
#define RCC_APB2ENR   (*(volatile uint32_t *)0x40023844)

// GPIOA
#define GPIOA_MODER   (*(volatile uint32_t *)0x40020000)
#define GPIOA_AFRL    (*(volatile uint32_t *)0x40020020)
#define GPIOA_ODR     (*(volatile uint32_t *)0x40020014)

// SPI1
#define SPI1_CR1      (*(volatile uint32_t *)0x40013000)
#define SPI1_CR2      (*(volatile uint32_t *)0x40013004)
#define SPI1_SR       (*(volatile uint32_t *)0x40013008)
#define SPI1_DR       (*(volatile uint32_t *)0x4001300C)

// SPI1_SR bits
#define SPI_SR_RXNE   (1 << 0)
#define SPI_SR_TXE    (1 << 1)

// LED on PA5 won't work anymore (used for SCK), so use built-in LED if available
// We'll use GPIOA pin 0 (A0) as a debug toggle — optional

int main(void) {
    // Step 1: Enable clocks
    RCC_AHB1ENR |= (1 << 0);   // GPIOA clock enable
    RCC_APB2ENR |= (1 << 12);  // SPI1 clock enable

    // Step 2: Configure PA5 (SCK), PA6 (MISO), PA7 (MOSI)
    //         to Alternate Function mode (MODER = 10)
    //         PA5=[11:10], PA6=[13:12], PA7=[15:14]
    GPIOA_MODER &= ~((3 << 10) | (3 << 12) | (3 << 14));
    GPIOA_MODER |=  ((2 << 10) | (2 << 12) | (2 << 14));

    // Set AF5 (SPI1) for PA5, PA6, PA7 in AFRL register
    // Each pin gets 4 bits in AFRL: PA5=[23:20], PA6=[27:24], PA7=[31:28]
    GPIOA_AFRL &= ~((0xF << 20) | (0xF << 24) | (0xF << 28));
    GPIOA_AFRL |=  ((5 << 20) | (5 << 24) | (5 << 28));

    // Step 3: Configure SPI1 as slave
    SPI1_CR1 = 0;              // Reset CR1
    // MSTR = 0 (slave mode) — already 0
    // CPOL = 0, CPHA = 0 (SPI mode 0 — must match Pi side)
    // DFF = 0 (8-bit data)
    // SSM = 1, SSI = 0 (software NSS, force slave selected)
    SPI1_CR1 |= (1 << 9);     // SSM = 1 (software slave management)

    SPI1_CR2 = 0;              // Reset CR2

    // Pre-load first response byte into DR
    SPI1_DR = 0xAA;

    // Enable SPI
    SPI1_CR1 |= (1 << 6);     // SPE = 1

    // Main loop: echo back every byte received (for latency testing)
    while (1) {
        if (SPI1_SR & SPI_SR_RXNE) {
            uint8_t received = (uint8_t)SPI1_DR;

            while (!(SPI1_SR & SPI_SR_TXE));
            SPI1_DR = received;  // echo exact same byte
        }
    }
}
